modLoader = "javafml"
loaderVersion = "[47,)"
#issueTrackerURL = ""
license = "GPL-3.0-or-later"

[[mods]]
modId = "betterux"
version = "${version}"
displayName = "Better UX"
authors = "rarepeepo"
description = '''
This mod adds various little UX improvements to enhance the overall user experience.
'''
logoFile = "assets/betterux/icon.png"
displayURL = "https://modrinth.com/mod/better-ux"

[[dependencies.betterux]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.betterux]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.betterux]]
modId = "architectury"
mandatory = true
versionRange = "[9.2.14,)"
ordering = "AFTER"
side = "BOTH"
