modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = ""
license = "GPL-3.0-or-later"

[[mods]]
modId = "betterux"
version = "${version}"
displayName = "Better UX"
authors = "rarepeepo"
description = '''
This mod adds various little UX improvements to enhance the overall user experience.
'''
logoFile = "assets/betterux/icon.png"
displayURL = "https://modrinth.com/mod/better-ux"

[[dependencies.betterux]]
modId = "neoforge"
mandatory = true
versionRange = "[20.5,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.betterux]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.5,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.betterux]]
modId = "architectury"
mandatory = true
versionRange = "[12.0.28,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "betterux.mixins.json"

[[mixins]]
config = "betterux.mixins.client.json"
